### PR TITLE
fix duplicate entries being added to the RecipeBook

### LINKED ISSUE #111: Fix Bug allowing duplicate entries
Fix bug which is allowing duplicate entries of the same recipe.

### PR DESCRIPTION
**Pull request by kevinswk94**
This PR is to fix #111

### CODE REVIEW

File: src/main/java/seedu/address/model/recipe/attribute/InstructionList.java [hunk 1]
```diff
@@ -10,7 +10,7 @@
  * Represents a Recipe's instructions in the recipe book.
  */
 public class InstructionList {
-    private final ArrayList<Instruction> instructionData;
+    public final ArrayList<Instruction> instructionData;
```
Comment (sharadhr) [inline src/main/java/seedu/address/model/recipe/attribute/InstructionList.java:13]: Why is this public? Instance variables should always be private; maybe declare and define an instance method, `List<Instruction> asList()` instead of exposing the variable?

File: src/main/java/seedu/address/model/recipe/attribute/Instruction.java [hunk 2]
```diff
@@ -12,7 +12,7 @@
     public static final String MESSAGE_CONSTRAINTS = "Each instruction should be "
             + "a non-blank string.";
 
-    private final String instructionString;
+    public final String instructionString;
```
Comment (sharadhr) [inline src/main/java/seedu/address/model/recipe/attribute/Instruction.java:15]: Once again, consider defining an accessor method for this

File: src/main/java/seedu/address/model/recipe/attribute/IngredientList.java [hunk 3]
```diff
@@ -44,6 +44,24 @@ public void deleteIngredient(Ingredient ingredient) {
         ingredientData.remove(ingredient);
     }
 
+    @Override
+    public boolean equals(Object other) {
```
Comment (sharadhr) [inline src/main/java/seedu/address/model/recipe/attribute/IngredientList.java:48]: Looks good; well-defined equality notion

**Review by sharadhr — DISMISSED** [review]

File: src/main/java/seedu/address/model/recipe/attribute/InstructionList.java (hunk 1 above)
Comment (kevinswk94) [reply src/main/java/seedu/address/model/recipe/attribute/InstructionList.java:13]: the other classes define their fields as public.

**Review by AdarshChugani — APPROVED** [review]
Looks Good! 👍 

Thanks Kev!
